### PR TITLE
fix: Do not panic on `StreamUpgradeError` in `on_connection_handler_event`

### LINKED ISSUE #2: bug: `StreamUpgradeError` not handled in `on_connection_handler_event`
https://github.com/romac/libp2p-scatter/blob/ea9014495d911fc17552cedbaa1d697aa509990c/src/lib.rs#L204

### PR DESCRIPTION
**Pull request by BastienFaivre**
fixes #2.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -229,7 +229,14 @@ impl NetworkBehaviour for Behaviour {
...
             }
-            Tx => {
+
+            Ok(Tx) => {
+                return;
+            }
+
+            Err(e) => {
+                tracing::debug!("ConnectionHandler error: {:?}", e);
+
```
Comment (romac) [inline src/lib.rs:239]:
```suggestion
                tracing::debug!("Failed to broadcast message: {e}");
```

Comment (romac) [reply src/lib.rs:239]: [In floodsub](https://docs.rs/libp2p-floodsub/0.45.0/src/libp2p_floodsub/layer.rs.html#367-370), they do this: 

```rust         
self.events.push_back(ToSwarm::CloseConnection {
    peer_id,
    connection: CloseConnection::One(connection_id),
});
```

Do you think it would make sense here as well?

**Review by romac — COMMENTED** [review]
Thanks a lot!

File: src/lib.rs (hunk 1 above)
Comment (BastienFaivre) [reply src/lib.rs:239]: I wondered what to put here, but what makes me doubtful is that floodsub seems to be the only rust-libp2p protocol to generate a `CloseConnection` event. In my intuition, if there were an issue when stream upgrading the connection, it would be the swarm's responsibility to cover the case and close the connection if needed.
However, I just saw that [this event](https://github.com/libp2p/rust-libp2p/blob/d0590a7a71160dcf806d38813b74925d3217a98c/swarm/src/behaviour.rs#L326) only closes the failed connection. In the worst case, the event is triggered twice, which is not a big deal as the second would not negatively impact the execution. Therefore, it is safe to follow the same idea. Moreover, keeping a failed connection alive is not useful at all.
I will update the code accordingly.
